bin: update imgur

diff --git a/bin/imgur b/bin/imgur
--- a/bin/imgur
+++ b/bin/imgur
@@ -1,115 +1,84 @@
 #!/bin/bash
 
-# imgur script by Bart Nagel <bart@tremby.net>
-# version 4
-# I release this into the public domain. Do with it what you will.
+# imgur script by Phil Tang <tangphillip@gmail.com>
+# Based the work of Bart Nagel <bart@tremby.net>
+# Shared with a Creative Commons Attribution 3.0 Unported License.
 
-# Required: curl
-#
-# Optional: xsel or xclip for automatically putting the URLs on the X selection 
-# for easy pasting
-#
-# Instructions:
-# Put it somewhere in your path and maybe rename it:
-# 	mv ~/Downloads/imgurbash.sh ~/bin/imgur
-# Make it executable:
-# 	chmod +x ~/bin/imgur
-# Optional, since Alan kindly provided an API key for this script: stick your 
-# API key in the top:
-# 	vim ~/bin/imgur
-# Upload an image:
-# 	imgur images/hilarious/manfallingover.jpg
-# Upload multiple images:
-# 	imgur images/delicious/cake.png images/exciting/bungeejump.jpg
-# The URLs will be displayed (and the delete page's URLs will be displayed on 
-# stderr). If you have xsel or xclip the URLs will also be put on the X 
-# selection, which you can usually paste with a middle click.
-
-# API Key provided by Alan@imgur.com
-apikey="b3625162d3418ac51a9ee805b1840452"
+# If you have rate limit issues, get your own key at http://api.imgur.com/
+CLIENT_ID="9657b96ca0b7f38"
+CLIPBOARD=true
 
 # function to output usage instructions
 function usage {
-	echo "Usage: $(basename $0) <filename> [<filename> [...]]" >&2
-	echo "Upload images to imgur and output their new URLs to stdout. Each one's" >&2
-	echo "delete page is output to stderr between the view URLs." >&2
-	echo "If xsel or xclip is available, the URLs are put on the X selection for" >&2
-	echo "easy pasting." >&2
+	echo "Usage: $(basename $0) <filename>
+Upload an image to imgur, print its URL to stdout, and print the delete page URL to stderr.
+If you're on a Mac or have xsel/xclip, copy the image URL to the clipboard." >&2
 }
 
 # check API key has been entered
-if [ "$apikey" = "Your API key" ]; then
+if [ "$CLIENT_ID" = "Your Client ID" ]; then
 	echo "You first need to edit the script and put your API key in the variable near the top." >&2
 	exit 15
 fi
 
 # check arguments
-if [ "$1" = "-h" -o "$1" = "--help" ]; then
+if [[ "$1" == "-h" || "$1" == "--help" ]]; then
 	usage
 	exit 0
-elif [ $# == 0 ]; then
-	echo "No file specified" >&2
+elif [[ "$1" == "-x" || "$1" == "--no-clipboard" ]]; then
+	CLIPBOARD=false
+	shift
+fi
+
+if [ $# -ne 1 ]; then
+	if [ $# == 0 ]; then
+		echo "No file specified." >&2
+	else
+		echo "Unexpected arguments" >&2
+	fi
 	usage
 	exit 16
+elif [ ! -f "$1" ]; then
+	echo "File \"$1\" not found" >&2
+	exit 1
 fi
 
 # check curl is available
-type curl >/dev/null 2>/dev/null || {
+which curl &>/dev/null || {
 	echo "Couln't find curl, which is required." >&2
 	exit 17
 }
 
-clip=""
-errors=false
-
-# loop through arguments
-while [ $# -gt 0 ]; do
-	file="$1"
-	shift
-
-	# check file exists
-	if [ ! -f "$file" ]; then
-		echo "file '$file' doesn't exist, skipping" >&2
-		errors=true
-		continue
-	fi
-
-	# upload the image
-	response=$(curl -F "key=$apikey" -H "Expect: " -F "image=@$file" \
-		http://imgur.com/api/upload.xml 2>/dev/null)
-	# the "Expect: " header is to get around a problem when using this through 
-	# the Squid proxy. Not sure if it's a Squid bug or what.
-	if [ $? -ne 0 ]; then
-		echo "Upload failed" >&2
-		errors=true
-		continue
-	elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
-		echo "Error message from imgur:" >&2
-		echo $response | sed -r 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
-		errors=true
-		continue
-	fi
-
-	# parse the response and output our stuff
-	url=$(echo $response | sed -r 's/.*<original_image>(.*)<\/original_image>.*/\1/')
-	deleteurl=$(echo $response | sed -r 's/.*<delete_page>(.*)<\/delete_page>.*/\1/')
-	echo $url
-	echo "Delete page: $deleteurl" >&2
-
-	# append the URL to a string so we can put them all on the clipboard later
-	clip="$clip$url
-"
-done
-
-# put the URLs on the clipboard if we have xsel or xclip
-if [ $DISPLAY ]; then
-	{ type xsel >/dev/null 2>/dev/null && echo -n $clip | xsel --clipboard; } \
-		|| { type xclip >/dev/null 2>/dev/null && echo -n $clip | xclip -selection clipboard; } \
-		|| echo "Haven't copied to the clipboard: no xsel or xclip" >&2
-else
-	echo "Haven't copied to the clipboard: no \$DISPLAY" >&2
+# upload the image
+# the "Expect: " header is to get around a problem when using this through the
+# Squid proxy. Not sure if it's a Squid bug or what.
+response=$(curl \
+	-H "Authorization: Client-ID $CLIENT_ID" \
+	-H "Expect: " \
+	-F "image=@$1" \
+	https://api.imgur.com/3/image 2>/dev/null)
+if [ $? -ne 0 ]; then
+	echo "Upload failed" >&2
+	exit 2
+elif [ $(echo $response | grep -c "<error_msg>") -gt 0 ]; then
+	echo "Error message from imgur:" >&2
+	echo $response | sed -E 's/.*<error_msg>(.*)<\/error_msg>.*/\1/' >&2
+	exit 3
+elif [[ "$response" != *deletehash* ]]; then
+	echo "Unknown Failure: Imgur is probably down for maintenance."
+	exit 4
 fi
 
-if $errors; then
-	exit 1
+# parse the response and output our stuff
+url=$(echo $response | sed -E 's/.*"link":"([^"]+)".*/\1/' | sed "s|\\\\/|/|g")
+deleteurl=$(echo $response | sed -E 's/.*"deletehash":"([^"]+)".*/\1/' | sed "s|^|http://imgur.com/delete/|")
+echo $url
+echo "Delete page: $deleteurl" >&2
+
+# put the URL on the clipboard if we have xsel or xclip
+if [ $CLIPBOARD == true ]; then
+	{ which pbcopy &>/dev/null && echo -n $url | pbcopy; } \
+		|| { which xsel &>/dev/null && echo -n $url | xsel --input --clipboard; } \
+		|| { which xclip &>/dev/null && echo -n $url | xclip -selection clipboard; } \
+		|| echo "Haven't copied to the clipboard: no pbcopy, xsel, or xclip" >&2
 fi
